### PR TITLE
Bla bla stuff... 

### PR DESCRIPTION
**Pull request by krushndayshmookh**

### CODE REVIEW

**Comment by krushndayshmookh** [comment]
Hello @ahdinosaur !

I need a little help regarding node js.
i want to make a file manager like website for getting files form my server to some remote device over the internet. just like this: http://raisoni.tk
I saw their front end code but it has nothing important for me.
The website is designed with php. but i want a node js backend. Can you suggest some ways to do that?

also i want to store data in json files. my node js server can read and write json using fs.readFile and fs.writeFile. but you see, for small files, i can do fs.readfile then json.parse and the for writing it can be json.stringyfy followed by fs.write. but it is not suitable for files having lots of data. Can you tell some way or module to append data to json files like an object??

waiting anxiously, 
@krushndayshmookh

**Comment by ahdinosaur** [comment]
hey @krushndayshmookh,

> i want to make a file manager like website for getting files form my server to some remote device over the internet.

sure, here's a simple example file server:

```js
const { stat, readdir, createReadStream } = require('fs')
const { createServer } = require('http')
const { join } = require('path')
const cwd = process.cwd()

const server = createServer((req, res) => {
  const path = join(cwd, req.url)
  stat(path, (err, stats) => {
    if (err) return handleError(err)
    if (stats.isDirectory()) {
      readdir(path, (err, files) => {
        if (err) return handleError(err)
        res.end(JSON.stringify(files, null, 2))
      })
    } else {
      createReadStream(path).pipe(res)
    }
  })

  function handleError (err) {
    console.error(err)
    res.statusCode = 500
    res.end()
  }
})

server.listen(3000)
```

```shell
cat "hello" > test.txt
node server.js
curl http://localhost:3000/test.txt
curl http://localhost:3000/
curl http://localhost:3000/nope.png
```

there might be some helpful resources on this style of Node.js here: https://nodeschool.io/#workshoppers.

> but it is not suitable for files having lots of data. Can you tell some way or module to append data to json files like an object??

you might be interested in a recent talk by a friend: https://www.youtube.com/watch?v=Yn-U6ygClyU

using node streams, you could either use something like [`JSONStream`](https://www.npmjs.com/package/JSONStream) to parse from within a large json object, or you could use [`ldjson-stream`](https://www.npmjs.com/package/ldjson-stream) to use "line-delimited json objects".

hope that helps yo.

**Comment by ahdinosaur** [comment]
oh yeah and maybe https://github.com/karissa/yo-fs

**Comment by krushndayshmookh** [comment]
Thanks a lot buddy!

**Pull request merged**
